on: pull_request

name: Check Code Style (checkpatch)

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      DL_DIR: ../downloads
      BUILD_DIR: ../build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Checkout Base
        run: |
            git fetch origin ${{ github.event.pull_request.base.ref }}
            echo "The current base for checkpatch is: $(git show FETCH_HEAD --oneline --raw)"
      - name: Install required packages (apt-get)
        run: |
            sudo apt-get update
            sudo apt-get install patchutils python3-ply python3-git
      - name: Run checkpatch
        run: |
            ./tools/scripts/checkpatch.pl --no-signoff --git FETCH_HEAD..HEAD
